spring.application.name=api

# Connexion à PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/sicklecare_db
spring.datasource.username=postgres
spring.datasource.password=@Young1234

# Gestion automatique des tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
